on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: pmishractrrgy.azurecr.io
        username: ${{ secrets.acr_pmishractrrgy_username }}
        password: ${{ secrets.acr_pmishractrrgy_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t pmishractrrgy.azurecr.io/k8spmishra:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push pmishractrrgy.azurecr.io/k8spmishra:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_k8spmishra_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep k8s-pmishra-ns | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace k8s-pmishra-ns`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: k8s-pmishra-ns
        container-registry-url: pmishractrrgy.azurecr.io
        container-registry-username: ${{ secrets.acr_pmishractrrgy_username }}
        container-registry-password: ${{ secrets.acr_pmishractrrgy_password }}
        secret-name: k8spmishradockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: k8s-pmishra-ns
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          pmishractrrgy.azurecr.io/k8spmishra:${{ github.sha }}
        imagepullsecrets: |
          k8spmishradockerauth
