name: Containerize to ACR

# on:
#   push:
#     branches: [main]
  
workflow_dispatch:

jobs:
  containerize:
    runs-on: ubuntu-latest

  steps:
    #checkout
    -uses: actions/checkout@v2

    #connect to ACR
    # -uses: ams/acr-task-github-action@v2
    #   with: