name: Azure Container Registry Build
on:
  push:
    branches: [main]

  workflow_dispatch:
  
jobs:
  Containerizer:
    runs-on: ubuntu-latest
    name: create containers
    
    steps:
      - uses: actions/checkout@v2
    
      - uses: ams0/acr-task-github-action@v2
        with:
          azure_service_principal:
          azure_service_principal_password:
          tenant: 
          # The name of the ACR, minus the .azurecr.io
          registry: 
          # Repository to use
          repository: 
          # Github access token for private repositories
          git_access_token: 
          # Docker image name
          image: # optional
          # Docker image tag, default to the commit SHA
          tag: # optional
          # Branch to build from, defaults to master
          branch: # optional
          # The folder in the Github repo that holds the source
          folder: 
          # The location of the Dockerfile; defaults to ./Dockerfile
          dockerfile: # optional
          # JSON specifying key=value pairs as as Docker build arguments
          build_args: # optional
